const entry = (id, name, adapter, ports = [], recipe = undefined) => ({ id, name, adapter, ports, recipe });

export const toolRecipes = [
  entry('mirofish', 'MiroFish', 'agent-framework', [3000, 5001], {
    install: ['git clone https://github.com/666ghj/MiroFish.git .', 'cp .env.example .env', 'npm run setup:all'],
    start: ['npm run dev'],
    stop: [],
    uiPort: 3000,
    healthPath: '/',
  }),
  entry('mirofish-offline', 'MiroFish Offline', 'agent-framework'),
  entry('camel', 'CAMEL', 'agent-framework'),
  entry('crewai', 'CrewAI', 'agent-framework'),
  entry('autogen', 'AutoGen', 'agent-framework'),
  entry('langgraph', 'LangGraph', 'agent-framework'),
  entry('metagpt', 'MetaGPT', 'agent-framework'),

  entry('voicebox', 'Voicebox', 'managed-service'),
  entry('openvoice', 'OpenVoice', 'cli'),
  entry('f5-tts', 'F5-TTS', 'managed-service'),
  entry('fish-speech', 'Fish Speech', 'managed-service'),
  entry('coqui-tts', 'Coqui TTS / XTTS', 'cli'),
  entry('whisperlive', 'WhisperLive', 'managed-service'),
  entry('whisper', 'Whisper', 'cli'),
  entry('realtimestt', 'RealtimeSTT', 'managed-service'),
  entry('ebook2audiobook', 'ebook2audiobook', 'managed-service'),
  entry('pdf-narrator', 'PDF Narrator', 'cli'),

  entry('triposr', 'TripoSR', 'managed-service'),
  entry('instantmesh', 'InstantMesh', 'managed-service'),
  entry('gaussian-splatting', 'Gaussian Splatting', 'cli'),
  entry('supersplat', 'SuperSplat', 'embedded-web'),
  entry('unirig', 'UniRig', 'managed-service'),
  entry('puppeteer-3d', 'Puppeteer', 'managed-service'),

  entry('comfyui', 'ComfyUI', 'managed-service', [8188], {
    install: ['git clone https://github.com/comfy-org/comfyui.git .', 'python -m pip install -r requirements.txt'],
    start: ['python main.py --listen 127.0.0.1 --port 8188'],
    stop: [],
    uiPort: 8188,
    healthPath: '/system_stats',
  }),
  entry('comfystudio', 'ComfyStudio', 'native-app'),
  entry('godot', 'Godot Engine', 'native-app', [], { start: ['godot'], executable: 'godot' }),
  entry('blender', 'Blender', 'native-app', [], { start: ['blender'], executable: 'blender' }),
  entry('penpot', 'Penpot', 'embedded-web'),

  entry('plane', 'Plane', 'embedded-web'),
  entry('wekan', 'WeKan', 'embedded-web'),
  entry('logseq', 'Logseq', 'native-app'),
  entry('appflowy', 'AppFlowy', 'native-app'),
  entry('twenty', 'Twenty CRM', 'embedded-web'),
  entry('documenso', 'Documenso', 'embedded-web'),
  entry('calcom', 'Cal.com', 'embedded-web'),
  entry('chatwoot', 'Chatwoot', 'embedded-web'),
  entry('formbricks', 'Formbricks', 'embedded-web'),
  entry('baserow', 'Baserow', 'embedded-web'),

  entry('freqtrade', 'Freqtrade', 'managed-service', [8080], {
    install: ['docker pull freqtradeorg/freqtrade:stable'],
    start: ['docker compose up -d'],
    stop: ['docker compose down'],
    uiPort: 8080,
    healthPath: '/api/v1/ping',
  }),
  entry('lean', 'LEAN', 'cli'),
  entry('ccxt', 'CCXT', 'library'),

  entry('ollama', 'Ollama', 'managed-service', [11434], {
    install: ['curl -fsSL https://ollama.com/install.sh | sh'],
    start: ['ollama serve'],
    stop: [],
    healthPath: '/api/tags',
    executable: 'ollama',
  }),
  entry('label-studio', 'Label Studio', 'managed-service', [8080], {
    install: ['python -m pip install label-studio'],
    start: ['label-studio start --host 127.0.0.1 --port 8080'],
    stop: [],
    uiPort: 8080,
    healthPath: '/health',
    executable: 'label-studio',
  }),
  entry('coolify', 'Coolify', 'embedded-web'),
  entry('litellm', 'LiteLLM', 'managed-service'),
  entry('open-webui', 'Open WebUI', 'embedded-web', [3000], {
    install: ['docker pull ghcr.io/open-webui/open-webui:main'],
    start: ['docker run -d -p 127.0.0.1:3000:8080 --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main'],
    stop: ['docker stop open-webui'],
    uiPort: 3000,
    healthPath: '/health',
  }),
  entry('dify', 'Dify', 'embedded-web'),
  entry('langflow', 'Langflow', 'embedded-web', [7860], {
    install: ['python -m pip install langflow'],
    start: ['langflow run --host 127.0.0.1 --port 7860'],
    stop: [],
    uiPort: 7860,
    healthPath: '/health',
    executable: 'langflow',
  }),
  entry('langfuse', 'Langfuse', 'embedded-web'),
  entry('qdrant', 'Qdrant', 'managed-service', [6333, 6334], {
    install: ['docker pull qdrant/qdrant'],
    start: ['docker run -d -p 127.0.0.1:6333:6333 -p 127.0.0.1:6334:6334 -v qdrant_storage:/qdrant/storage --name qdrant qdrant/qdrant'],
    stop: ['docker stop qdrant'],
    uiPort: 6333,
    healthPath: '/healthz',
  }),
  entry('metabase', 'Metabase', 'embedded-web'),
  entry('uptime-kuma', 'Uptime Kuma', 'embedded-web', [3001], {
    install: ['docker pull louislam/uptime-kuma:2'],
    start: ['docker run -d --restart=always -p 127.0.0.1:3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:2'],
    stop: ['docker stop uptime-kuma'],
    uiPort: 3001,
    healthPath: '/',
  }),
  entry('posthog', 'PostHog', 'embedded-web'),
  entry('minio', 'MinIO', 'managed-service'),

  entry('openhands', 'OpenHands', 'embedded-web'),
  entry('continue', 'Continue', 'native-app'),
  entry('aider', 'Aider', 'cli'),
  entry('playwright', 'Playwright', 'library'),
  entry('appsmith', 'Appsmith', 'embedded-web'),
  entry('docling', 'Docling', 'cli'),
  entry('meilisearch', 'Meilisearch', 'managed-service', [7700], {
    install: ['docker pull getmeili/meilisearch:latest'],
    start: ['docker run -d -p 127.0.0.1:7700:7700 -v meili_data:/meili_data --name meilisearch getmeili/meilisearch:latest'],
    stop: ['docker stop meilisearch'],
    healthPath: '/health',
  }),
];

export const toolRecipeMap = new Map(toolRecipes.map(recipe => [recipe.id, recipe]));
